# Generated by Django 3.1.1 on 2020-09-09 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_view',
            new_name='is_viewed',
        ),
    ]
