# Generated by Django 3.1.1 on 2020-09-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200909_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(default=None, max_length=255, null=True)),
                ('api_id', models.PositiveIntegerField(default=None, help_text='getting from https://my.telegram.org/auth', null=True)),
                ('api_hash', models.CharField(default=None, help_text='getting from https://my.telegram.org/auth', max_length=255, null=True)),
                ('is_active', models.BooleanField(blank=True, default=False, help_text='non active config is not working', null=True)),
                ('is_bot', models.BooleanField(blank=True, default=None, help_text='select if you want to use bot account for this config', null=True)),
                ('bot_token', models.CharField(blank=True, default=None, help_text='required if you use bot account.use @botfather for create a bot or get token for available bot.', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'config',
                'verbose_name_plural': 'configs',
            },
        ),
    ]
